server:
    port: 8080
    contextPath: /
    disableUploadTimeout: false
    session:
        timeout: 10200
    cloud:
        loadbalancer:
          retry:
            enabled: true 

spring:
    application:
        name: provider-fabric
    http:
        multipart:
            max-file-size: 100000MB
            max-request-size: 100000MB
            maxFileSize: 100000MB
            maxRequestSize: 100000MB

 
feign:
    httpclient:
        enabled:true
   
logging:
  level:
    root: INFO
  file: logs/fabric.log
  maxHistory:



eureka:
  client:
    serviceUrl:
      defaultZone: http://192.168.37.40:8765/eureka/
  instance:
    prefer-ip-address: true

